"use client";

import { useCallback, useState } from "react";

import { AdminHeader } from "@/components/layout/AdminHeader";
import {
  HistoricalImportBadge,
  HistoricalRecordsTable,
} from "@/components/historical/HistoricalRecords";
import {
  applyQuery,
  emptyQuery,
  FilterButton,
  type TableColumn,
  type TableQuery,
} from "@/components/ui/FilterControls";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { useToast } from "@/components/ui/Toast";
import { pageSlice, Pagination, TableShell, Td, Th } from "@/components/ui/Table";
import { errorMessage } from "@/lib/api";
import {
  certificateValidity,
  listSeminarProgressRows,
} from "@/lib/api/seminarProgress";
import { fetchCertificateFileBlob } from "@/lib/api/seminars";
import {
  buildCertificateBlob,
  certificateDateLabel,
  presentBlob,
} from "@/lib/certificate";
import { useAutoRefresh, type LoadMode } from "@/lib/useAutoRefresh";
import { formatSlashDate } from "@/lib/format";
import type { SeminarProgressRow } from "@/types/admin";

/* Display labels for the derived validity status. */
const VALIDITY_LABELS: Record<string, string> = {
  NOT_ISSUED: "Not Issued",
  VALID: "Valid",
  EXPIRED: "Expired",
};

function validityDateLabel(row: SeminarProgressRow): string {
  return row.certificateIssuedAt && row.certificateValidUntil
    ? formatSlashDate(row.certificateValidUntil.slice(0, 10))
    : "N/A";
}

const COLUMNS: Array<TableColumn<SeminarProgressRow>> = [
  { key: "customerNumber", label: "Customer ID #", get: (row) => row.customerNumber },
  { key: "name", label: "Name", get: (row) => row.name },
  {
    key: "occupationLocation",
    label: "Occupation & Location",
    get: (row) => row.occupationLocation,
  },
  { key: "contactNumber", label: "Contact #", get: (row) => row.contactNumber },
  { key: "email", label: "Email", get: (row) => row.email },
  { key: "facebookName", label: "Facebook", get: (row) => row.facebookName },
  { key: "status", label: "Status", get: (row) => row.status },
  { key: "modules", label: "Module #", get: (row) => row.modules },
  { key: "seminarId", label: "Seminar ID #", get: (row) => row.seminarId },
  {
    key: "registrationDate",
    label: "Registration Date",
    get: (row) => row.registrationDate,
  },
  { key: "payDate", label: "Pay Date", get: (row) => row.payDate },
  { key: "address", label: "Address", get: (row) => row.address },
  {
    key: "validityDate",
    label: "Validity Date",
    get: (row) => validityDateLabel(row),
  },
  {
    key: "certificateValidityStatus",
    label: "Certificate Validity Status",
    get: (row) =>
      VALIDITY_LABELS[
        certificateValidity(row.certificateIssuedAt, row.certificateValidUntil)
      ],
  },
];

const TABLE_COLUMN_COUNT = 15; // 12 data columns + validity date/status + actions

/*
 * Customer Seminar Progress — data source: staff
 * GET /api/seminars/progress (one row per enrolled customer).
 *
 * Certificates are generated by DACS automatically the moment a
 * customer completes Seminar Modules 1-3: the backend stamps the issue
 * date and validUntil (+2 years) on the record, so this table only
 * READS them — Validity Date, Certificate Validity Status and the
 * View/Download actions all follow from the certificate itself, with
 * no staff upload, replace or issue step.
 */
export default function SeminarProgressPage() {
  const [search, setSearch] = useState("");
  const [query, setQuery] = useState<TableQuery>(emptyQuery("customerNumber"));
  const [page, setPage] = useState(0);
  const [rows, setRows] = useState<SeminarProgressRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  /* "live" = DACS e-learning enrollments; "historical" = imported legacy
     seminar attendance (clearly separated — different semantics). */
  const [view, setView] = useState<"live" | "historical">("live");

  /* Certificate View/Download state. */
  const { showToast } = useToast();
  const [busyRequestId, setBusyRequestId] = useState<string | null>(null);

  const load = useCallback(async (mode: LoadMode) => {
    try {
      setRows(await listSeminarProgressRows());
      setLoadError(null);
    } catch (error) {
      /* Background refreshes keep the last good rows; the next tick retries. */
      if (mode === "initial") {
        setLoadError(
          errorMessage(error, "Unable to load seminar progress. Please try again.")
        );
      }
    } finally {
      setLoading(false);
    }
  }, []);

  /* Farmers progress through modules from the customer site. */
  useAutoRefresh(load, 30_000);

  /*
   * View opens the certificate in a new tab; Download saves it. Both
   * resolve the SAME artifact the customer gets: the stored file when
   * a record still carries one from the retired manual workflow,
   * otherwise the certificate rendered from the record itself.
   */
  async function openCertificate(row: SeminarProgressRow, download: boolean) {
    if (!row.certificateRequestId || busyRequestId) return;
    setBusyRequestId(row.certificateRequestId);
    try {
      if (row.hasCertificateFile) {
        const blob = await fetchCertificateFileBlob(row.certificateRequestId);
        presentBlob(
          blob,
          row.certificateFileName ?? `certificate-${row.seminarId}`,
          download
        );
        return;
      }

      /* Both come from the generated record; a row without them is not
         a certificate this table can render. */
      if (!row.certificateIssuedAt || row.seminarId === "N/A") {
        throw new Error("This certificate is not ready yet.");
      }

      const blob = await buildCertificateBlob({
        recipientName: row.name,
        certificateNumber: row.seminarId,
        issuedAtLabel: certificateDateLabel(row.certificateIssuedAt),
      });
      presentBlob(blob, `dacs-certificate-${row.seminarId}.jpg`, download);
    } catch (error) {
      showToast(
        errorMessage(error, "Unable to open the certificate."),
        "error"
      );
    } finally {
      setBusyRequestId(null);
    }
  }

  const searched = rows.filter((row) =>
    `${row.customerNumber} ${row.name} ${row.email} ${row.status}`
      .toLowerCase()
      .includes(search.toLowerCase())
  );
  const filtered = applyQuery(searched, COLUMNS, query);
  const paged = pageSlice(filtered, page);

  function renderActions(row: SeminarProgressRow) {
    /* Certificates exist only after Modules 1-3 are complete (the
       backend generates one automatically at that moment). Until then
       there is nothing to act on — and no way for staff to shortcut
       the seminar by issuing one by hand. */
    if (!row.certificateRequestId) {
      return (
        <span
          className="text-dacs-muted"
          title="Available once the customer completes Seminar Modules 1-3"
        >
          —
        </span>
      );
    }

    /* Expired certificates keep View/Download: the record is history,
       not something that disappears at the 2-year mark. */
    const busy = busyRequestId === row.certificateRequestId;

    return (
      <div className="flex flex-wrap items-center gap-x-3 gap-y-1">
        <button
          type="button"
          disabled={busy}
          onClick={() => openCertificate(row, false)}
          className="font-semibold text-dacs-red underline hover:opacity-80 disabled:opacity-50"
          title={row.certificateFileName ?? undefined}
        >
          View
        </button>
        <button
          type="button"
          disabled={busy}
          onClick={() => openCertificate(row, true)}
          className="font-semibold text-dacs-red underline hover:opacity-80 disabled:opacity-50"
        >
          Download
        </button>
      </div>
    );
  }

  return (
    <>
      <AdminHeader
        title="Customer Seminar Progress"
        search={view === "live" ? { value: search, onChange: setSearch } : undefined}
        right={
          view === "live" ? (
            <FilterButton
              rows={rows}
              columns={COLUMNS}
              query={query}
              onChange={setQuery}
            />
          ) : undefined
        }
      />

      {/* Live e-learning enrollments vs. imported legacy attendance. */}
      <div className="mb-5 flex flex-wrap items-center gap-2">
        <button
          type="button"
          onClick={() => setView("live")}
          className={`rounded-full px-5 py-2 font-semibold transition-colors ${
            view === "live"
              ? "bg-dacs-dark text-white"
              : "border border-dacs-dark/30 text-dacs-muted hover:text-dacs-dark"
          }`}
        >
          Live Enrollments
        </button>
        <button
          type="button"
          onClick={() => setView("historical")}
          className={`rounded-full px-5 py-2 font-semibold transition-colors ${
            view === "historical"
              ? "bg-dacs-dark text-white"
              : "border border-dacs-dark/30 text-dacs-muted hover:text-dacs-dark"
          }`}
        >
          Historical Imports
        </button>
        {view === "historical" && (
          <span className="ml-2 flex flex-wrap items-center gap-2 text-sm text-dacs-muted">
            <HistoricalImportBadge />
            Legacy seminar attendance from imported spreadsheets — not DACS
            e-learning enrollments.
          </span>
        )}
      </div>

      {view === "historical" && (
        <HistoricalRecordsTable
          recordType="SEMINAR"
          searchPlaceholder="Search historical seminar records..."
        />
      )}

      {view === "live" && (
      <TableShell>
        <thead>
          <tr>
            <Th>Customer ID #</Th>
            <Th>Name</Th>
            <Th>Occupation &amp; Location</Th>
            <Th>Contact #</Th>
            <Th>Email</Th>
            <Th>Facebook</Th>
            <Th>Status</Th>
            <Th>Module #</Th>
            <Th>Seminar ID #</Th>
            <Th>Registration Date</Th>
            <Th>Pay Date</Th>
            <Th>Address</Th>
            <Th>Validity Date</Th>
            <Th>Certificate Validity Status</Th>
            <Th>Actions</Th>
          </tr>
        </thead>
        <tbody>
          {loading && (
            <tr>
              <Td className="py-10 text-dacs-muted" colSpan={TABLE_COLUMN_COUNT}>
                Loading seminar progress…
              </Td>
            </tr>
          )}
          {!loading && loadError && (
            <tr>
              <Td className="py-10 text-dacs-muted" colSpan={TABLE_COLUMN_COUNT}>
                {loadError}
              </Td>
            </tr>
          )}
          {!loading && !loadError && paged.map((row) => (
            <tr key={row.id ?? row.customerNumber}>
              <Td>{row.customerNumber}</Td>
              <Td className="font-semibold text-dacs-red">{row.name}</Td>
              <Td>{row.occupationLocation}</Td>
              <Td>{row.contactNumber}</Td>
              <Td>{row.email}</Td>
              <Td>{row.facebookName}</Td>
              <Td>
                <StatusBadge status={row.status} />
              </Td>
              <Td>{row.modules}</Td>
              <Td>{row.seminarId}</Td>
              <Td>{row.registrationDate ? formatSlashDate(row.registrationDate) : "N/A"}</Td>
              <Td>{row.payDate ? formatSlashDate(row.payDate) : "N/A"}</Td>
              <Td>{row.address}</Td>
              {/* Certificate valid until issuedAt + 2 years; N/A pre-issue. */}
              <Td>{validityDateLabel(row)}</Td>
              <Td>
                {/* Derived from validUntil at render time — never stored,
                    so certificates flip to Expired automatically. */}
                <StatusBadge
                  status={certificateValidity(
                    row.certificateIssuedAt,
                    row.certificateValidUntil
                  )}
                />
              </Td>
              <Td>{renderActions(row)}</Td>
            </tr>
          ))}
          {!loading && !loadError && paged.length === 0 && (
            <tr>
              <Td className="py-10 text-dacs-muted" colSpan={TABLE_COLUMN_COUNT}>
                No customers match the current search/filter.
              </Td>
            </tr>
          )}
        </tbody>
      </TableShell>
      )}

      {view === "live" && (
        <Pagination page={page} total={filtered.length} onPageChange={setPage} />
      )}
    </>
  );
}
